name: Test
on:
  push:
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: ubuntu:16.04

    steps:
      - uses: actions/checkout@v2
     
      - uses: iTrooz/keepalive-workflow@master